armor = [
	{"name":"Leather Headgear","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"50","level":1}]}, 
	{"name":"Leather Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[]}, 
	{"name":"Leather Gloves","part":"arms","rank":"low","slots":["0","0","0"],"skills":[]}, 
	{"name":"Leather Belt","part":"waist","rank":"low","slots":["0","0","0"],"skills":[]}, 
	{"name":"Leather Trousers","part":"legs","rank":"low","slots":["0","0","0"],"skills":[]}, 
	{"name":"Chainmail Headgear","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"61","level":1}]}, 
	{"name":"Chainmail Vest","part":"chest","rank":"low","slots":["0","0","0"],"skills":[]}, 
	{"name":"Chainmail Gloves","part":"arms","rank":"low","slots":["0","0","0"],"skills":[]}, 
	{"name":"Chainmail Belt","part":"waist","rank":"low","slots":["0","0","0"],"skills":[]}, 
	{"name":"Chainmail Trousers","part":"legs","rank":"low","slots":["0","0","0"],"skills":[]}, 
	{"name":"Hunter's Headgear","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"84","level":1}]}, 
	{"name":"Hunter's Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"87","level":1}]}, 
	{"name":"Hunter's Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"97","level":1}]}, 
	{"name":"Hunter's Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"82","level":1}]}, 
	{"name":"Hunter's Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"6","level":1}]}, 
	{"name":"Bone Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"44","level":1}]}, 
	{"name":"Bone Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"5","level":1}]}, 
	{"name":"Bone Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"88","level":1}]}, 
	{"name":"Bone Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"49","level":1}]}, 
	{"name":"Bone Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"30","level":1}]}, 
	{"name":"Vespoid Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"77","level":1}]}, 
	{"name":"Vespoid Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"107","level":1}]}, 
	{"name":"Vespoid Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"68","level":1}]}, 
	{"name":"Vespoid Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"69","level":1}]}, 
	{"name":"Vespoid Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"48","level":1}]}, 
	{"name":"Kestodon Guards","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"0","level":1}]}, 
	{"name":"Gajau Boots","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"3","level":1}]}, 
	{"name":"Jagras Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"91","level":1}]}, 
	{"name":"Jagras Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"53","level":1}]}, 
	{"name":"Jagras Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"67","level":1}]}, 
	{"name":"Jagras Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"38","level":1}]}, 
	{"name":"Jagras Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"90","level":1}]}, 
	{"name":"Kulu Headpiece","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"34","level":1}]}, 
	{"name":"Kulu Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"95","level":1}]}, 
	{"name":"Kulu Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"76","level":1}]}, 
	{"name":"Kulu Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"55","level":1}]}, 
	{"name":"Kulu Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"20","level":1}]}, 
	{"name":"Alloy Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"107","level":1}]}, 
	{"name":"Alloy Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"104","level":1}]}, 
	{"name":"Alloy Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"21","level":1}]}, 
	{"name":"Alloy Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"74","level":1}]}, 
	{"name":"Alloy Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"92","level":1}]}, 
	{"name":"Pukei Hood","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"93","level":1}]}, 
	{"name":"Pukei Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"55","level":1}]}, 
	{"name":"Pukei Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"74","level":1}]}, 
	{"name":"Pukei Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"73","level":1}]}, 
	{"name":"Pukei Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"13","level":1}]}, 
	{"name":"Barroth Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"42","level":1}]}, 
	{"name":"Barroth Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"96","level":1}]}, 
	{"name":"Barroth Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"59","level":1}]}, 
	{"name":"Barroth Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"64","level":1}]}, 
	{"name":"Barroth Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"98","level":1}]}, 
	{"name":"Jyura Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"3","level":1}]}, 
	{"name":"Jyura Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"64","level":1}]}, 
	{"name":"Jyura Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"103","level":1}]}, 
	{"name":"Jyura Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"52","level":1}]}, 
	{"name":"Jyura Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"36","level":1}]}, 
	{"name":"Kadachi Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"17","level":1}]}, 
	{"name":"Kadachi Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"56","level":1}]}, 
	{"name":"Kadachi Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"31","level":1}]}, 
	{"name":"Kadachi Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"99","level":1}]}, 
	{"name":"Kadachi Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"100","level":1}]}, 
	{"name":"High Metal Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"52","level":1}]}, 
	{"name":"High Metal Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"27","level":1}]}, 
	{"name":"High Metal Braces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"21","level":1}]}, 
	{"name":"High Metal Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"14","level":1}]}, 
	{"name":"High Metal Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"46","level":1}]}, 
	{"name":"King Beetle Vertex","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"32","level":1}]}, 
	{"name":"King Beetle Thorax","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"77","level":1}]}, 
	{"name":"King Beetle Brachia","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"58","level":1}]}, 
	{"name":"King Beetle Elytra","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"48","level":1}]}, 
	{"name":"King Beetle Crura","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"37","level":1}]}, 
	{"name":"Butterfly Vertex","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"32","level":1}]}, 
	{"name":"Butterfly Thorax","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"77","level":1}]}, 
	{"name":"Butterfly Barchia","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"58","level":1}]}, 
	{"name":"Butterfly Elytra","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"48","level":1}]}, 
	{"name":"Butterfly Crura","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"37","level":1}]}, 
	{"name":"Shamos Goggles","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"22","level":1}]}, 
	{"name":"Hornetaur Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"26","level":1}]}, 
	{"name":"Hornetaur Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"29","level":1}]}, 
	{"name":"Hornetaur Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"40","level":1}]}, 
	{"name":"Hornetaur Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"15","level":1}]}, 
	{"name":"Hornetaur Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"43","level":1}]}, 
	{"name":"Anja Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"33","level":1}],"set_bonus_id":"0"}, 
	{"name":"Anja Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"59","level":1}],"set_bonus_id":"0"}, 
	{"name":"Anja Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"89","level":1}],"set_bonus_id":"0"}, 
	{"name":"Anja Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"34","level":1}],"set_bonus_id":"0"}, 
	{"name":"Anja Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"4","level":1}],"set_bonus_id":"0"}, 
	{"name":"Rathian Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"44","level":1}]}, 
	{"name":"Rathian Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"13","level":1}]}, 
	{"name":"Rathian Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"73","level":1}]}, 
	{"name":"Rathian Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"74","level":1}]}, 
	{"name":"Rathian Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"79","level":1}]}, 
	{"name":"Tzitzi Headgear","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"11","level":1}]}, 
	{"name":"Tzitzi Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"17","level":1}]}, 
	{"name":"Tzitzi Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"98","level":1}]}, 
	{"name":"Tzitzi Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"106","level":1}]}, 
	{"name":"Tzitzi Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"86","level":1}]}, 
	{"name":"Lumu Hat","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"95","level":1}]}, 
	{"name":"Lumu Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"62","level":1}]}, 
	{"name":"Lumu Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"4","level":1}]}, 
	{"name":"Lumu Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"23","level":1}]}, 
	{"name":"Lumu Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"107","level":1}]}, 
	{"name":"Girros Mask","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"49","level":1}]}, 
	{"name":"Girros Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"69","level":1}]}, 
	{"name":"Girros Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"67","level":1}]}, 
	{"name":"Girros Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"29","level":1}]}, 
	{"name":"Girros Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"68","level":1}]}, 
	{"name":"Baan Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"88","level":1}]}, 
	{"name":"Baan Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"86","level":1}]}, 
	{"name":"Baan Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"85","level":1}]}, 
	{"name":"Baan Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"42","level":1}]}, 
	{"name":"Baan Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"9","level":1}]}, 
	{"name":"Ingot Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"99","level":1}]}, 
	{"name":"Ingot Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"100","level":1}]}, 
	{"name":"Ingot Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"44","level":1}]}, 
	{"name":"Ingot Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"107","level":1}]}, 
	{"name":"Ingot Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"21","level":1}]}, 
	{"name":"Death Stench Brain","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"81","level":1}]}, 
	{"name":"Death Stench Muscle","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"38","level":1}]}, 
	{"name":"Death Stench Grip","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"36","level":1}]}, 
	{"name":"Death Stench Bowels","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"24","level":1}]}, 
	{"name":"Death Stench Heels","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"43","level":1}]}, 
	{"name":"Brigade Lobos","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"78","level":1}]}, 
	{"name":"Brigade Suit","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"23","level":1}]}, 
	{"name":"Brigade Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"46","level":1}]}, 
	{"name":"Brigade Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"41","level":1}]}, 
	{"name":"Brigade Boots","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"83","level":1}]}, 
	{"name":"Legiana Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"23","level":1}],"set_bonus_id":"20"}, 
	{"name":"Legiana Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"32","level":1}],"set_bonus_id":"20"}, 
	{"name":"Legiana Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"2","level":1}],"set_bonus_id":"20"}, 
	{"name":"Legiana Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"51","level":1}],"set_bonus_id":"20"}, 
	{"name":"Legiana Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"52","level":1}],"set_bonus_id":"20"}, 
	{"name":"Odogaron Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"9","level":1}],"set_bonus_id":"10"}, 
	{"name":"Odogaron Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"92","level":1}],"set_bonus_id":"10"}, 
	{"name":"Odogaron Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"17","level":1}],"set_bonus_id":"10"}, 
	{"name":"Odogaron Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"20","level":1}],"set_bonus_id":"10"}, 
	{"name":"Odogaron Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"77","level":1}],"set_bonus_id":"10"}, 
	{"name":"Rathalos Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"5","level":1}],"set_bonus_id":"13"}, 
	{"name":"Rathalos Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"105","level":1}],"set_bonus_id":"13"}, 
	{"name":"Rathalos Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"34","level":1}],"set_bonus_id":"13"}, 
	{"name":"Rathalos Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"33","level":1}],"set_bonus_id":"13"}, 
	{"name":"Rathalos Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"56","level":1}],"set_bonus_id":"13"}, 
	{"name":"Diablos Helm","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"19","level":1}],"set_bonus_id":"4"}, 
	{"name":"Diablos Mail","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"88","level":1}],"set_bonus_id":"4"}, 
	{"name":"Diablos Vambraces","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"47","level":1}],"set_bonus_id":"4"}, 
	{"name":"Diablos Coil","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"59","level":1}],"set_bonus_id":"4"}, 
	{"name":"Diablos Greaves","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"102","level":1}],"set_bonus_id":"4"}, 
	{"name":"Kirin Horn","part":"head","rank":"low","slots":["0","0","0"],"skills":[{"id":"59","level":1}],"set_bonus_id":"6"}, 
	{"name":"Kirin Jacket","part":"chest","rank":"low","slots":["0","0","0"],"skills":[{"id":"23","level":1}],"set_bonus_id":"6"}, 
	{"name":"Kirin Longarms","part":"arms","rank":"low","slots":["0","0","0"],"skills":[{"id":"10","level":1}],"set_bonus_id":"6"}, 
	{"name":"Kirin Hoop","part":"waist","rank":"low","slots":["0","0","0"],"skills":[{"id":"99","level":1}],"set_bonus_id":"6"}, 
	{"name":"Kirin Leg Guards","part":"legs","rank":"low","slots":["0","0","0"],"skills":[{"id":"100","level":1}],"set_bonus_id":"6"}, 
	{"name":"Leather Headgear α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"50","level":2}]}, 
	{"name":"Leather Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"34","level":1}]}, 
	{"name":"Leather Gloves α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"78","level":1}]}, 
	{"name":"Leather Belt α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"95","level":1}]}, 
	{"name":"Leather Trousers α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"16","level":1}]}, 
	{"name":"Leather Headgear β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"50","level":1}]}, 
	{"name":"Leather Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[]}, 
	{"name":"Leather Gloves β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[]}, 
	{"name":"Leather Belt β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[]}, 
	{"name":"Leather Trousers β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[]}, 
	{"name":"Chainmail Headgear α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"61","level":1},{"id":"42","level":1}]}, 
	{"name":"Chainmail Armor α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"104","level":1}]}, 
	{"name":"Chainmail Gloves α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"78","level":1}]}, 
	{"name":"Chainmail Belt α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"77","level":1}]}, 
	{"name":"Chainmail Trousers α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"79","level":1}]}, 
	{"name":"Chainmail Headgear β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"61","level":1}]}, 
	{"name":"Chainmail Armor β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[]}, 
	{"name":"Chainmail Gloves β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[]}, 
	{"name":"Chainmail Belt β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[]}, 
	{"name":"Chainmail Trousers β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[]}, 
	{"name":"Hunter's Headgear α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"84","level":1},{"id":"83","level":1}]}, 
	{"name":"Hunter's Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"87","level":2}]}, 
	{"name":"Hunter's Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"97","level":2}]}, 
	{"name":"Hunter's Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"97","level":1},{"id":"61","level":1}]}, 
	{"name":"Hunter's Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"87","level":1},{"id":"82","level":1}]}, 
	{"name":"Hunter's Headgear β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"84","level":1}]}, 
	{"name":"Hunter's Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"87","level":1}]}, 
	{"name":"Hunter's Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"97","level":1}]}, 
	{"name":"Hunter's Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"61","level":1}]}, 
	{"name":"Hunter's Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"82","level":1}]}, 
	{"name":"Bone Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"44","level":1},{"id":"30","level":1}]}, 
	{"name":"Bone Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"5","level":1}]}, 
	{"name":"Bone Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"88","level":1},{"id":"5","level":1}]}, 
	{"name":"Bone Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"49","level":1},{"id":"60","level":1}]}, 
	{"name":"Bone Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"30","level":2}]}, 
	{"name":"Bone Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"44","level":1}]}, 
	{"name":"Bone Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"5","level":1}]}, 
	{"name":"Bone Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"88","level":1}]}, 
	{"name":"Bone Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"49","level":1}]}, 
	{"name":"Bone Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"30","level":1}]}, 
	{"name":"Alloy Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"107","level":1},{"id":"21","level":1}]}, 
	{"name":"Alloy Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"104","level":2}]}, 
	{"name":"Alloy Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"21","level":1},{"id":"92","level":1}]}, 
	{"name":"Alloy Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"74","level":1},{"id":"104","level":1}]}, 
	{"name":"Alloy Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"92","level":2}]}, 
	{"name":"Alloy Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"107","level":1}]}, 
	{"name":"Alloy Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"104","level":1}]}, 
	{"name":"Alloy Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"21","level":1}]}, 
	{"name":"Alloy Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"74","level":1}]}, 
	{"name":"Alloy Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"92","level":1}]}, 
	{"name":"King Beetle Vertex α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"32","level":2},{"id":"13","level":1}]}, 
	{"name":"King Beetle Thorax α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"77","level":2},{"id":"13","level":1}]}, 
	{"name":"King Beetle Brachia α","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"13","level":2},{"id":"58","level":1}]}, 
	{"name":"King Beetle Elytra α","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"48","level":1},{"id":"77","level":1}]}, 
	{"name":"King Beetle Crura α","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"37","level":1},{"id":"32","level":1}]}, 
	{"name":"King Beetle Vertex β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"32","level":2}]}, 
	{"name":"King Beetle Thorax β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"77","level":2}]}, 
	{"name":"King Beetle Brachia β","part":"arms","rank":"high","slots":["2","1","0"],"skills":[{"id":"13","level":2}]}, 
	{"name":"King Beetle Elytra β","part":"waist","rank":"high","slots":["2","1","0"],"skills":[{"id":"48","level":1}]}, 
	{"name":"King Beetle Crura β","part":"legs","rank":"high","slots":["2","1","0"],"skills":[{"id":"37","level":1}]}, 
	{"name":"Butterfly Vertex α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"13","level":1},{"id":"32","level":2}]}, 
	{"name":"Butterfly Thorax α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"13","level":1},{"id":"77","level":2}]}, 
	{"name":"Butterfly Brachia α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"13","level":2},{"id":"58","level":1}]}, 
	{"name":"Butterfly Elytra α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"48","level":1},{"id":"77","level":1}]}, 
	{"name":"Butterfly Crura α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"37","level":1},{"id":"32","level":1}]}, 
	{"name":"Butterfly Vertex β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"32","level":2}]}, 
	{"name":"Butterfly Thorax β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"77","level":2}]}, 
	{"name":"Butterfly Brachia β","part":"arms","rank":"high","slots":["2","1","0"],"skills":[{"id":"13","level":2}]}, 
	{"name":"Butterfly Elytra β","part":"waist","rank":"high","slots":["2","1","0"],"skills":[{"id":"48","level":1}]}, 
	{"name":"Butterfly Crura β","part":"legs","rank":"high","slots":["2","1","0"],"skills":[{"id":"37","level":1}]}, 
	{"name":"Vespoid Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"77","level":1},{"id":"68","level":1}]}, 
	{"name":"Vespoid Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"107","level":1}]}, 
	{"name":"Vespoid Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"68","level":1}]}, 
	{"name":"Vespoid Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"69","level":2}]}, 
	{"name":"Vespoid Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"48","level":1},{"id":"69","level":1}]}, 
	{"name":"Vespoid Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"77","level":1}]}, 
	{"name":"Vespoid Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"107","level":1}]}, 
	{"name":"Vespoid Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"68","level":1}]}, 
	{"name":"Vespoid Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"69","level":1}]}, 
	{"name":"Vespoid Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"48","level":1}]}, 
	{"name":"Hornetaur Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"26","level":1},{"id":"24","level":1}]}, 
	{"name":"Hornetaur Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"29","level":1},{"id":"50","level":1}]}, 
	{"name":"Hornetaur Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"40","level":1},{"id":"50","level":1}]}, 
	{"name":"Hornetaur Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"15","level":1},{"id":"50","level":1}]}, 
	{"name":"Hornetaur Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"43","level":1},{"id":"24","level":1}]}, 
	{"name":"Hornetaur Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"26","level":1}]}, 
	{"name":"Hornetaur Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"29","level":1}]}, 
	{"name":"Hornetaur Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"40","level":1}]}, 
	{"name":"Hornetaur Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"15","level":1}]}, 
	{"name":"Hornetaur Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"43","level":1}]}, 
	{"name":"Mosswine Mask α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"65","level":2}]}, 
	{"name":"Kestodon Guards α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"0","level":1},{"id":"36","level":1}]}, 
	{"name":"Kestodon Guards β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"0","level":1}]}, 
	{"name":"Gajau Boots α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"3","level":2},{"id":"103","level":1}]}, 
	{"name":"Gajau Boots β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"3","level":1},{"id":"103","level":1}]}, 
	{"name":"Shamos Goggles α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"22","level":1},{"id":"41","level":1}]}, 
	{"name":"Shamos Goggles β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"22","level":1}]}, 
	{"name":"Jagras Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"91","level":2}]}, 
	{"name":"Jagras Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"53","level":2}]}, 
	{"name":"Jagras Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"67","level":1},{"id":"53","level":1}]}, 
	{"name":"Jagras Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"38","level":1},{"id":"91","level":1}]}, 
	{"name":"Jagras Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"90","level":1},{"id":"40","level":1}]}, 
	{"name":"Jagras Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"91","level":1}]}, 
	{"name":"Jagras Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"53","level":1}]}, 
	{"name":"Jagras Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"67","level":1}]}, 
	{"name":"Jagras Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"38","level":1}]}, 
	{"name":"Jagras Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"90","level":1}]}, 
	{"name":"Kulu Headpiece α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"34","level":1},{"id":"105","level":1}]}, 
	{"name":"Kulu Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"95","level":1},{"id":"20","level":1}]}, 
	{"name":"Kulu Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"76","level":1},{"id":"20","level":1}]}, 
	{"name":"Kulu Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"55","level":2}]}, 
	{"name":"Kulu Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"20","level":1},{"id":"55","level":1}]}, 
	{"name":"Kulu Headpiece β","part":"head","rank":"high","slots":["1","1","0"],"skills":[{"id":"34","level":1}]}, 
	{"name":"Kulu Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"95","level":1}]}, 
	{"name":"Kulu Vambraces β","part":"arms","rank":"high","slots":["2","0","0"],"skills":[{"id":"76","level":1}]}, 
	{"name":"Kulu Coil β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"55","level":1}]}, 
	{"name":"Kulu Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"20","level":1}]}, 
	{"name":"Tzitzi Headgear α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"11","level":1},{"id":"98","level":1}]}, 
	{"name":"Tzitzi Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"17","level":1},{"id":"103","level":2}]}, 
	{"name":"Tzitzi Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"98","level":2},{"id":"106","level":1}]}, 
	{"name":"Tzitzi Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"106","level":2},{"id":"103","level":1}]}, 
	{"name":"Tzitzi Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"86","level":2}]}, 
	{"name":"Tzitzi Headgear β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"11","level":1}]}, 
	{"name":"Tzitzi Mail β","part":"chest","rank":"high","slots":["1","1","0"],"skills":[{"id":"17","level":1}]}, 
	{"name":"Tzitzi Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"98","level":2}]}, 
	{"name":"Tzitzi Coil β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"106","level":1}]}, 
	{"name":"Tzitzi Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"86","level":1}]}, 
	{"name":"Girros Mask α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"49","level":1},{"id":"69","level":1}]}, 
	{"name":"Girros Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"69","level":2}]}, 
	{"name":"Girros Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"67","level":2}]}, 
	{"name":"Girros Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"29","level":1},{"id":"68","level":1}]}, 
	{"name":"Girros Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"68","level":2}]}, 
	{"name":"Girros Mask β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"49","level":1}]}, 
	{"name":"Girros Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"69","level":1}]}, 
	{"name":"Girros Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"67","level":1}]}, 
	{"name":"Girros Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"29","level":1}]}, 
	{"name":"Girros Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"68","level":1}]}, 
	{"name":"Pukei Hood α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"93","level":2}]}, 
	{"name":"Pukei Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"55","level":1},{"id":"13","level":1}]}, 
	{"name":"Pukei Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"74","level":2},{"id":"73","level":1}]}, 
	{"name":"Pukei Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"73","level":2}]}, 
	{"name":"Pukei Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"13","level":2},{"id":"93","level":1}]}, 
	{"name":"Pukei Hood β","part":"head","rank":"high","slots":["1","1","0"],"skills":[{"id":"93","level":1}]}, 
	{"name":"Pukei Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"55","level":1}]}, 
	{"name":"Pukei Vambraces β","part":"arms","rank":"high","slots":["1","1","0"],"skills":[{"id":"74","level":1}]}, 
	{"name":"Pukei Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"73","level":1}]}, 
	{"name":"Pukei Greaves β","part":"legs","rank":"high","slots":["2","0","0"],"skills":[{"id":"13","level":1}]}, 
	{"name":"Barroth Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"42","level":2}]}, 
	{"name":"Barroth Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"96","level":2}]}, 
	{"name":"Barroth Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"59","level":1},{"id":"96","level":1}]}, 
	{"name":"Barroth Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"64","level":1},{"id":"42","level":1}]}, 
	{"name":"Barroth Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"98","level":2},{"id":"59","level":1}]}, 
	{"name":"Barroth Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"42","level":1}]}, 
	{"name":"Barroth Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"96","level":1}]}, 
	{"name":"Barroth Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"59","level":1}]}, 
	{"name":"Barroth Coil β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"64","level":1}]}, 
	{"name":"Barroth Greaves β","part":"legs","rank":"high","slots":["1","1","0"],"skills":[{"id":"98","level":1}]}, 
	{"name":"Anja Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"33","level":2},{"id":"34","level":1}],"set_bonus_id":"1"}, 
	{"name":"Anja Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"59","level":1},{"id":"89","level":1}],"set_bonus_id":"1"}, 
	{"name":"Anja Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"89","level":1},{"id":"33","level":1}],"set_bonus_id":"1"}, 
	{"name":"Anja Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"34","level":2},{"id":"4","level":1}],"set_bonus_id":"1"}, 
	{"name":"Anja Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"4","level":2}],"set_bonus_id":"1"}, 
	{"name":"Anja Helm β","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"33","level":2}],"set_bonus_id":"1"}, 
	{"name":"Anja Mail β","part":"chest","rank":"high","slots":["1","1","0"],"skills":[{"id":"59","level":1}],"set_bonus_id":"1"}, 
	{"name":"Anja Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"89","level":1}],"set_bonus_id":"1"}, 
	{"name":"Anja Coil β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"34","level":2}],"set_bonus_id":"1"}, 
	{"name":"Anja Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"4","level":1}],"set_bonus_id":"1"}, 
	{"name":"Jyura Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"3","level":2}]}, 
	{"name":"Jyura Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"64","level":1},{"id":"103","level":1}]}, 
	{"name":"Jyura Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"103","level":2},{"id":"3","level":1}]}, 
	{"name":"Jyura Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"52","level":2}]}, 
	{"name":"Jyura Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"36","level":2}]}, 
	{"name":"Jyura Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"3","level":1}]}, 
	{"name":"Jyura Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"64","level":1}]}, 
	{"name":"Jyura Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"103","level":2}]}, 
	{"name":"Jyura Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"52","level":1}]}, 
	{"name":"Jyura Greaves β","part":"legs","rank":"high","slots":["2","0","0"],"skills":[{"id":"36","level":1}]}, 
	{"name":"Kadachi Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"17","level":2}]}, 
	{"name":"Kadachi Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"56","level":1},{"id":"31","level":1}]}, 
	{"name":"Kadachi Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"31","level":2}]}, 
	{"name":"Kadachi Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"99","level":2},{"id":"100","level":1}]}, 
	{"name":"Kadachi Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"100","level":2},{"id":"17","level":1}]}, 
	{"name":"Kadachi Helm β","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"17","level":1}]}, 
	{"name":"Kadachi Mail β","part":"chest","rank":"high","slots":["2","0","0"],"skills":[{"id":"56","level":1}]}, 
	{"name":"Kadachi Vambraces β","part":"arms","rank":"high","slots":["2","0","0"],"skills":[{"id":"31","level":1}]}, 
	{"name":"Kadachi Coil β","part":"waist","rank":"high","slots":["1","1","0"],"skills":[{"id":"99","level":1}]}, 
	{"name":"Kadachi Greaves β","part":"legs","rank":"high","slots":["1","1","0"],"skills":[{"id":"100","level":1}]}, 
	{"name":"Lumu Hat α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"95","level":2}]}, 
	{"name":"Lumu Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"62","level":1},{"id":"4","level":1}]}, 
	{"name":"Lumu Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"4","level":2}]}, 
	{"name":"Lumu Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"23","level":2}]}, 
	{"name":"Lumu Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"107","level":1},{"id":"95","level":1}]}, 
	{"name":"Lumu Hat β","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"95","level":1}]}, 
	{"name":"Lumu Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"62","level":1}]}, 
	{"name":"Lumu Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"4","level":1}]}, 
	{"name":"Lumu Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"23","level":1}]}, 
	{"name":"Lumu Greaves β","part":"legs","rank":"high","slots":["1","1","0"],"skills":[{"id":"107","level":1}]}, 
	{"name":"Rathian Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"44","level":2},{"id":"73","level":1}]}, 
	{"name":"Rathian Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"13","level":2},{"id":"79","level":1}]}, 
	{"name":"Rathian Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"73","level":2}]}, 
	{"name":"Rathian Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"74","level":2},{"id":"44","level":1}]}, 
	{"name":"Rathian Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"79","level":2}]}, 
	{"name":"Rathian Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"44","level":1},{"id":"73","level":1}]}, 
	{"name":"Rathian Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"13","level":1},{"id":"79","level":1}]}, 
	{"name":"Rathian Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"73","level":1}]}, 
	{"name":"Rathian Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"74","level":1},{"id":"44","level":1}]}, 
	{"name":"Rathian Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"79","level":1}]}, 
	{"name":"Rath Heart Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"31","level":1},{"id":"73","level":1}],"set_bonus_id":"12"}, 
	{"name":"Rath Heart Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"101","level":2}],"set_bonus_id":"12"}, 
	{"name":"Rath Heart Braces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"107","level":2}],"set_bonus_id":"12"}, 
	{"name":"Rath Heart Coil α","part":"waist","slots":["0","0","0"],"skills":[{"id":"43","level":1},{"id":"74","level":1}],"set_bonus_id":"12"}, 
	{"name":"Rath Heart Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"101","level":1},{"id":"107","level":1}],"set_bonus_id":"12"}, 
	{"name":"Rath Heart Helm β","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"31","level":1}],"set_bonus_id":"12"}, 
	{"name":"Rath Heart Mail β","part":"chest","rank":"high","slots":["1","1","0"],"skills":[{"id":"101","level":1}],"set_bonus_id":"12"}, 
	{"name":"Rath Heart Braces β","part":"arms","rank":"high","slots":["2","0","0"],"skills":[{"id":"107","level":1}],"set_bonus_id":"12"}, 
	{"name":"Rath Heart Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"43","level":1}],"set_bonus_id":"12"}, 
	{"name":"Rath Heart Greaves β","part":"legs","rank":"high","slots":["2","0","0"],"skills":[{"id":"101","level":1}],"set_bonus_id":"12"}, 
	{"name":"Baan Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"102","level":2}]}, 
	{"name":"Baan Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"85","level":1},{"id":"9","level":1}]}, 
	{"name":"Baan Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"85","level":2},{"id":"42","level":1}]}, 
	{"name":"Baan Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"42","level":2}]}, 
	{"name":"Baan Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"9","level":2}]}, 
	{"name":"Baan Helm β","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"102","level":1}]}, 
	{"name":"Baan Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"85","level":1}]}, 
	{"name":"Baan Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"85","level":1},{"id":"42","level":1}]}, 
	{"name":"Baan Coil β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"42","level":1}]}, 
	{"name":"Baan Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"9","level":1}]}, 
	{"name":"Gastodon Horn α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"35","level":1},{"id":"8","level":1}]}, 
	{"name":"Gastodon Horn β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"35","level":1}]}, 
	{"name":"Barnos Jacket α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"45","level":1},{"id":"54","level":1}]}, 
	{"name":"Barnos Jacket β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"45","level":1}]}, 
	{"name":"Dodogama Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"8","level":2}]}, 
	{"name":"Dodogama Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"7","level":2}]}, 
	{"name":"Dodogama Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"12","level":2}]}, 
	{"name":"Dodogama Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"4","level":2},{"id":"8","level":1}]}, 
	{"name":"Dodogama Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"14","level":1},{"id":"7","level":1}]}, 
	{"name":"Dodogama Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"8","level":1}]}, 
	{"name":"Dodogama Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"7","level":1}]}, 
	{"name":"Dodogama Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"12","level":1}]}, 
	{"name":"Dodogama Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"4","level":2}]}, 
	{"name":"Dodogama Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"14","level":1}]}, 
	{"name":"Zorah Headgear α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"43","level":1},{"id":"7","level":1}],"set_bonus_id":"19"}, 
	{"name":"Zorah Hide α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"7","level":2},{"id":"107","level":1}],"set_bonus_id":"19"}, 
	{"name":"Zorah Claws α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"39","level":1},{"id":"12","level":1}],"set_bonus_id":"19"}, 
	{"name":"Zorah Spine α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"38","level":1},{"id":"102","level":1}],"set_bonus_id":"19"}, 
	{"name":"Zorah Spurs α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"12","level":2},{"id":"27","level":1}],"set_bonus_id":"19"}, 
	{"name":"Zorah Headgear β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"43","level":1}],"set_bonus_id":"19"}, 
	{"name":"Zorah Hide β","part":"chest","rank":"high","slots":["2","0","0"],"skills":[{"id":"7","level":2}],"set_bonus_id":"19"}, 
	{"name":"Zorah Claws β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"39","level":1}],"set_bonus_id":"19"}, 
	{"name":"Zorah Spine β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"38","level":1}],"set_bonus_id":"19"}, 
	{"name":"Zorah Spurs β","part":"legs","rank":"high","slots":["2","0","0"],"skills":[{"id":"12","level":2}],"set_bonus_id":"19"}, 
	{"name":"High Metal Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"52","level":2},{"id":"27","level":1}]}, 
	{"name":"High Metal Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"27","level":2},{"id":"51","level":1}]}, 
	{"name":"High Metal Braces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"21","level":2},{"id":"51","level":1}]}, 
	{"name":"High Metal Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"14","level":1},{"id":"21","level":1}]}, 
	{"name":"High Metal Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"46","level":1},{"id":"52","level":1}]}, 
	{"name":"High Metal Helm β","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"52","level":2}]}, 
	{"name":"High Metal Mail β","part":"chest","rank":"high","slots":["2","0","0"],"skills":[{"id":"27","level":1},{"id":"51","level":1}]}, 
	{"name":"High Metal Braces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"21","level":2}]}, 
	{"name":"High Metal Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"14","level":1}]}, 
	{"name":"High Metal Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"46","level":1}]}, 
	{"name":"Ingot Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"99","level":2}]}, 
	{"name":"Ingot Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"100","level":2}]}, 
	{"name":"Ingot Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"44","level":2},{"id":"99","level":1}]}, 
	{"name":"Ingot Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"107","level":2}]}, 
	{"name":"Ingot Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"21","level":2},{"id":"107","level":1}]}, 
	{"name":"Ingot Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"99","level":1}]}, 
	{"name":"Ingot Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"100","level":1}]}, 
	{"name":"Ingot Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"44","level":2}]}, 
	{"name":"Ingot Coil β","part":"waist","rank":"high","slots":["3","0","0"],"skills":[{"id":"107","level":1}]}, 
	{"name":"Ingot Greaves β","part":"legs","rank":"high","slots":["2","0","0"],"skills":[{"id":"21","level":2}]}, 
	{"name":"Brigade Lobos α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"78","level":2},{"id":"49","level":1}]}, 
	{"name":"Brigade Suit α","part":"chest","rank":"high","slots":["2","0","0"],"skills":[{"id":"23","level":2}]}, 
	{"name":"Brigade Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"46","level":2},{"id":"23","level":1}]}, 
	{"name":"Brigade Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"41","level":2},{"id":"78","level":1}]}, 
	{"name":"Brigade Boots α","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"83","level":1},{"id":"41","level":1}]}, 
	{"name":"Brigade Lobos β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"78","level":2}]}, 
	{"name":"Brigade Suit β","part":"chest","rank":"high","slots":["2","2","0"],"skills":[{"id":"23","level":1}]}, 
	{"name":"Brigade Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"46","level":2}]}, 
	{"name":"Brigade Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"41","level":2}]}, 
	{"name":"Brigade Boots β","part":"legs","rank":"high","slots":["3","0","0"],"skills":[{"id":"83","level":1}]}, 
	{"name":"Faux Felyne α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"67","level":3}]}, 
	{"name":"Strategist Spectacles α","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"20","level":2}]}, 
	{"name":"Lavasioth Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"33","level":2},{"id":"77","level":1}]}, 
	{"name":"Lavasioth Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"33","level":2},{"id":"45","level":1}]}, 
	{"name":"Lavasioth Vambraces α","part":"arms","rank":"high","slots":["2","0","0"],"skills":[{"id":"0","level":1},{"id":"106","level":1}]}, 
	{"name":"Lavasioth Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"77","level":2},{"id":"79","level":1}]}, 
	{"name":"Lavasioth Greaves α","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"94","level":1},{"id":"33","level":1}]}, 
	{"name":"Lavasioth Helm β","part":"head","rank":"high","slots":["1","1","0"],"skills":[{"id":"33","level":1},{"id":"77","level":1}]}, 
	{"name":"Lavasioth Mail β","part":"chest","rank":"high","slots":["1","1","0"],"skills":[{"id":"33","level":2}]}, 
	{"name":"Lavasioth Vambraces β","part":"arms","rank":"high","slots":["3","0","0"],"skills":[{"id":"0","level":1}]}, 
	{"name":"Lavasioth Coil β","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"77","level":2}]}, 
	{"name":"Lavasioth Greaves β","part":"legs","rank":"high","slots":["2","0","0"],"skills":[{"id":"94","level":1}]}, 
	{"name":"Legiana Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"23","level":2},{"id":"51","level":1}],"set_bonus_id":"21"}, 
	{"name":"Legiana Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"32","level":2},{"id":"23","level":1}],"set_bonus_id":"21"}, 
	{"name":"Legiana Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"2","level":1},{"id":"32","level":1}],"set_bonus_id":"21"}, 
	{"name":"Legiana Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"51","level":2},{"id":"107","level":1}],"set_bonus_id":"21"}, 
	{"name":"Legiana Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"52","level":2},{"id":"19","level":1}],"set_bonus_id":"21"}, 
	{"name":"Legiana Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"23","level":2}],"set_bonus_id":"21"}, 
	{"name":"Legiana Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"32","level":2}],"set_bonus_id":"21"}, 
	{"name":"Legiana Vambraces β","part":"arms","rank":"high","slots":["3","0","0"],"skills":[{"id":"2","level":1}],"set_bonus_id":"21"}, 
	{"name":"Legiana Coil β","part":"waist","slots":["2","0","0"],"skills":[{"id":"51","level":2}],"set_bonus_id":"21"}, 
	{"name":"Legiana Greaves β","part":"legs","rank":"high","slots":["3","0","0"],"skills":[{"id":"52","level":2}],"set_bonus_id":"21"}, 
	{"name":"Odogaron Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"9","level":2},{"id":"20","level":1}],"set_bonus_id":"11"}, 
	{"name":"Odogaron Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"92","level":2},{"id":"9","level":1}],"set_bonus_id":"11"}, 
	{"name":"Odogaron Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"17","level":1},{"id":"20","level":1}],"set_bonus_id":"11"}, 
	{"name":"Odogaron Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"20","level":2},{"id":"92","level":1}],"set_bonus_id":"11"}, 
	{"name":"Odogaron Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"77","level":1},{"id":"20","level":1}],"set_bonus_id":"11"}, 
	{"name":"Odogaron Helm β","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"9","level":2}],"set_bonus_id":"11"}, 
	{"name":"Odogaron Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"92","level":2}],"set_bonus_id":"11"}, 
	{"name":"Odogaron Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"17","level":1}],"set_bonus_id":"11"}, 
	{"name":"Odogaron Coil β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"20","level":2}],"set_bonus_id":"11"}, 
	{"name":"Odogaron Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"77","level":1}],"set_bonus_id":"11"}, 
	{"name":"Rathalos Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"5","level":2},{"id":"33","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rathalos Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"105","level":2},{"id":"33","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rathalos Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"34","level":2},{"id":"5","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rathalos Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"33","level":2},{"id":"36","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rathalos Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"56","level":1},{"id":"105","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rathalos Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"5","level":2}],"set_bonus_id":"14"}, 
	{"name":"Rathalos Mail β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"105","level":2}],"set_bonus_id":"14"}, 
	{"name":"Rathalos Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"34","level":2}],"set_bonus_id":"14"}, 
	{"name":"Rathalos Coil β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"33","level":2}],"set_bonus_id":"14"}, 
	{"name":"Rathalos Greaves β","part":"legs","rank":"high","slots":["3","0","0"],"skills":[{"id":"56","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rath Soul Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"18","level":1},{"id":"53","level":2}],"set_bonus_id":"14"}, 
	{"name":"Rath Soul Mail α","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"39","level":1},{"id":"53","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rath Soul Braces α","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"36","level":1},{"id":"107","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rath Soul Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"107","level":2},{"id":"72","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rath Soul Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"36","level":1},{"id":"16","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rath Soul Helm β","part":"head","rank":"high","slots":["1","1","0"],"skills":[{"id":"18","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rath Soul Mail β","part":"chest","rank":"high","slots":["2","0","0"],"skills":[{"id":"39","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rath Soul Braces β","part":"arms","rank":"high","slots":["2","0","0"],"skills":[{"id":"36","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rath Soul Coil β","part":"waist","rank":"high","slots":["3","0","0"],"skills":[{"id":"107","level":1}],"set_bonus_id":"14"}, 
	{"name":"Rath Soul Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"36","level":1}],"set_bonus_id":"14"}, 
	{"name":"Diablos Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"19","level":2},{"id":"47","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"88","level":2},{"id":"47","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"47","level":2},{"id":"102","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"59","level":2},{"id":"19","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"102","level":2},{"id":"88","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Helm β","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"19","level":2}],"set_bonus_id":"5"}, 
	{"name":"Diablos Mail β","part":"chest","rank":"high","slots":["2","0","0"],"skills":[{"id":"88","level":2}],"set_bonus_id":"5"}, 
	{"name":"Diablos Vambraces β","part":"arms","rank":"high","slots":["2","0","0"],"skills":[{"id":"47","level":2}],"set_bonus_id":"5"}, 
	{"name":"Diablos Coil β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"59","level":2}],"set_bonus_id":"5"}, 
	{"name":"Diablos Greaves β","part":"legs","rank":"high","slots":["1","1","0"],"skills":[{"id":"102","level":2}],"set_bonus_id":"5"}, 
	{"name":"Diablos Nero Helm α","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"36","level":2}],"set_bonus_id":"5"}, 
	{"name":"Diablos Nero Mail α","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"80","level":2}],"set_bonus_id":"5"}, 
	{"name":"Diablos Nero Braces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"36","level":1},{"id":"59","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Nero Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"80","level":1},{"id":"70","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Nero Greaves α","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"66","level":1},{"id":"47","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Nero Helm β","part":"head","rank":"high","slots":["3","0","0"],"skills":[{"id":"36","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Nero Mail β","part":"chest","rank":"high","slots":["2","1","0"],"skills":[{"id":"80","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Nero Braces β","part":"arms","rank":"high","slots":["2","1","0"],"skills":[{"id":"36","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Nero Coil β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"80","level":1}],"set_bonus_id":"5"}, 
	{"name":"Diablos Nero Greaves β","part":"legs","rank":"high","slots":["2","0","0"],"skills":[{"id":"66","level":1}],"set_bonus_id":"5"}, 
	{"name":"Uragaan Helm α","part":"head","rank":"high","slots":["3","0","0"],"skills":[{"id":"100","level":2}],"set_bonus_id":"16"}, 
	{"name":"Uragaan Mail α","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"70","level":2}],"set_bonus_id":"16"}, 
	{"name":"Uragaan Vambraces α","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"42","level":1},{"id":"21","level":1}],"set_bonus_id":"16"}, 
	{"name":"Uragaan Coil α","part":"waist","rank":"high","slots":["1","1","0"],"skills":[{"id":"70","level":1},{"id":"100","level":1}],"set_bonus_id":"16"}, 
	{"name":"Uragaan Greaves α","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"42","level":2}],"set_bonus_id":"16"}, 
	{"name":"Uragaan Helm β","part":"head","rank":"high","slots":["3","1","0"],"skills":[{"id":"100","level":1}],"set_bonus_id":"16"}, 
	{"name":"Uragaan Mail β","part":"chest","rank":"high","slots":["3","0","0"],"skills":[{"id":"70","level":1}],"set_bonus_id":"16"}, 
	{"name":"Uragaan Vambraces β","part":"arms","rank":"high","slots":["2","0","0"],"skills":[{"id":"42","level":1}],"set_bonus_id":"16"}, 
	{"name":"Uragaan Coil β","part":"waist","rank":"high","slots":["2","1","0"],"skills":[{"id":"70","level":1}],"set_bonus_id":"16"}, 
	{"name":"Uragaan Greaves β","part":"legs","rank":"high","slots":["3","0","0"],"skills":[{"id":"42","level":1}],"set_bonus_id":"16"}, 
	{"name":"Bazel Helm α","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"27","level":2},{"id":"7","level":1}],"set_bonus_id":"2"}, 
	{"name":"Bazel Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"42","level":2},{"id":"8","level":2}],"set_bonus_id":"2"}, 
	{"name":"Bazel Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"19","level":2},{"id":"27","level":1}],"set_bonus_id":"2"}, 
	{"name":"Bazel Coil α","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"27","level":2},{"id":"56","level":1}],"set_bonus_id":"2"}, 
	{"name":"Bazel Greaves α","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"12","level":2},{"id":"19","level":1}],"set_bonus_id":"2"}, 
	{"name":"Bazel Helm β","part":"head","rank":"high","slots":["3","1","0"],"skills":[{"id":"27","level":2}],"set_bonus_id":"2"}, 
	{"name":"Bazel Mail β","part":"chest","rank":"high","slots":["1","1","0"],"skills":[{"id":"42","level":2}],"set_bonus_id":"2"}, 
	{"name":"Bazel Vambraces β","part":"arms","rank":"high","slots":["3","0","0"],"skills":[{"id":"19","level":2}],"set_bonus_id":"2"}, 
	{"name":"Bazel Coil β","part":"waist","rank":"high","slots":["3","0","0"],"skills":[{"id":"27","level":2}],"set_bonus_id":"2"}, 
	{"name":"Bazel Greaves β","part":"legs","rank":"high","slots":["3","0","0"],"skills":[{"id":"12","level":2}],"set_bonus_id":"2"}, 
	{"name":"Damascus Helm α","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"21","level":2},{"id":"92","level":1}]}, 
	{"name":"Damascus Mail α","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"36","level":2},{"id":"21","level":2}]}, 
	{"name":"Damascus Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"43","level":1},{"id":"92","level":1}]}, 
	{"name":"Damascus Coil α","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"36","level":1},{"id":"54","level":2}]}, 
	{"name":"Damascus Greaves α","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"21","level":2},{"id":"54","level":1}]}, 
	{"name":"Damascus Helm β","part":"head","rank":"high","slots":["3","0","0"],"skills":[{"id":"21","level":2}]}, 
	{"name":"Damascus Mail β","part":"chest","rank":"high","slots":["1","1","1"],"skills":[{"id":"36","level":2}]}, 
	{"name":"Damascus Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"43","level":1}]}, 
	{"name":"Damascus Coil β","part":"waist","rank":"high","slots":["1","1","1"],"skills":[{"id":"36","level":1}]}, 
	{"name":"Damascus Greaves β","part":"legs","rank":"high","slots":["3","0","0"],"skills":[{"id":"21","level":2}]}, 
	{"name":"Dober Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"39","level":1},{"id":"25","level":1}]}, 
	{"name":"Dober Mail α","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"5","level":2},{"id":"65","level":1}]}, 
	{"name":"Dober Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"95","level":2},{"id":"65","level":1}]}, 
	{"name":"Dober Coil α","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"25","level":2},{"id":"5","level":1}]}, 
	{"name":"Dober Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"5","level":2},{"id":"95","level":1}]}, 
	{"name":"Dober Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"39","level":1}]}, 
	{"name":"Dober Mail β","part":"chest","rank":"high","slots":["2","0","0"],"skills":[{"id":"5","level":2}]}, 
	{"name":"Dober Vambraces β","part":"arms","rank":"high","slots":["1","1","0"],"skills":[{"id":"95","level":1},{"id":"65","level":1}]}, 
	{"name":"Dober Coil β","part":"waist","rank":"high","slots":["3","0","0"],"skills":[{"id":"25","level":2}]}, 
	{"name":"Dober Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"5","level":2}]}, 
	{"name":"Death Stench Brain α","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"81","level":1},{"id":"20","level":1}]}, 
	{"name":"Death Stench Muscle α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"38","level":1},{"id":"39","level":1}]}, 
	{"name":"Death Stench Grip α","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"36","level":2},{"id":"24","level":1}]}, 
	{"name":"Death Stench Bowels α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"24","level":2},{"id":"36","level":1}]}, 
	{"name":"Death Stench Heel α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"43","level":2},{"id":"24","level":2}]}, 
	{"name":"Death Stench Brain β","part":"head","rank":"high","slots":["3","0","0"],"skills":[{"id":"81","level":1}]}, 
	{"name":"Death Stench Muscle β","part":"chest","rank":"high","slots":["3","0","0"],"skills":[{"id":"38","level":1}]}, 
	{"name":"Death Stench Grip β","part":"arms","rank":"high","slots":["1","1","0"],"skills":[{"id":"36","level":2}]}, 
	{"name":"Death Stench Bowels β","part":"waist","rank":"high","slots":["1","1","0"],"skills":[{"id":"24","level":2}]}, 
	{"name":"Death Stench Heel β","part":"legs","rank":"high","slots":["1","1","0"],"skills":[{"id":"43","level":2}]}, 
	{"name":"Skull Mask α","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"43","level":1}]}, 
	{"name":"Nergigante Helm α","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"63","level":2},{"id":"5","level":1}],"set_bonus_id":"9"}, 
	{"name":"Nergigante Mail α","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"95","level":2},{"id":"1","level":1}],"set_bonus_id":"9"}, 
	{"name":"Nergigante Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"1","level":2},{"id":"5","level":1}],"set_bonus_id":"9"}, 
	{"name":"Nergigante Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"5","level":2},{"id":"95","level":1}],"set_bonus_id":"9"}, 
	{"name":"Nergigante Greaves α","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"63","level":1},{"id":"1","level":1}],"set_bonus_id":"9"}, 
	{"name":"Nergigante Helm β","part":"head","rank":"high","slots":["1","1","0"],"skills":[{"id":"63","level":2}],"set_bonus_id":"9"}, 
	{"name":"Nergigante Mail β","part":"chest","rank":"high","slots":["2","1","0"],"skills":[{"id":"95","level":2}],"set_bonus_id":"9"}, 
	{"name":"Nergigante Vambraces β","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"1","level":2}],"set_bonus_id":"9"}, 
	{"name":"Nergigante Coil β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"5","level":2}],"set_bonus_id":"9"}, 
	{"name":"Nergigante Greaves β","part":"legs","rank":"high","slots":["2","0","0"],"skills":[{"id":"63","level":1}],"set_bonus_id":"9"}, 
	{"name":"Kaiser Crown α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"57","level":2}],"set_bonus_id":"15"}, 
	{"name":"Kaiser Mail α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"89","level":2},{"id":"57","level":1}],"set_bonus_id":"15"}, 
	{"name":"Kaiser Vambraces α","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"105","level":2}],"set_bonus_id":"15"}, 
	{"name":"Kaiser Coil α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"7","level":2},{"id":"105","level":1}],"set_bonus_id":"15"}, 
	{"name":"Kaiser Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"57","level":2},{"id":"7","level":1}],"set_bonus_id":"15"}, 
	{"name":"Kaiser Crown β","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"57","level":1}],"set_bonus_id":"15"}, 
	{"name":"Kaiser Mail β","part":"chest","rank":"high","slots":["1","1","0"],"skills":[{"id":"89","level":2}],"set_bonus_id":"15"}, 
	{"name":"Kaiser Vambraces β","part":"arms","rank":"high","slots":["3","0","0"],"skills":[{"id":"105","level":1}],"set_bonus_id":"15"}, 
	{"name":"Kaiser Coil β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"7","level":2}],"set_bonus_id":"15"}, 
	{"name":"Kaiser Greaves β","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"57","level":2}],"set_bonus_id":"15"}, 
	{"name":"Kushala Glare α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"51","level":2},{"id":"43","level":1}],"set_bonus_id":"8"}, 
	{"name":"Kushala Cista α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"43","level":2},{"id":"36","level":1}],"set_bonus_id":"8"}, 
	{"name":"Kushala Grip α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"32","level":2},{"id":"43","level":1}],"set_bonus_id":"8"}, 
	{"name":"Kushala Cocoon α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"51","level":2},{"id":"31","level":1}],"set_bonus_id":"8"}, 
	{"name":"Kushala Crus α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"31","level":2},{"id":"43","level":1}],"set_bonus_id":"8"}, 
	{"name":"Kushala Glare β","part":"head","rank":"high","slots":["1","1","1"],"skills":[{"id":"51","level":2}],"set_bonus_id":"8"}, 
	{"name":"Kushala Cista β","part":"chest","rank":"high","slots":["2","0","0"],"skills":[{"id":"43","level":2}],"set_bonus_id":"8"}, 
	{"name":"Kushala Grip β","part":"arms","rank":"high","slots":["3","0","0"],"skills":[{"id":"32","level":2}],"set_bonus_id":"8"}, 
	{"name":"Kushala Cocoon β","part":"waist","rank":"high","slots":["1","1","0"],"skills":[{"id":"51","level":2}],"set_bonus_id":"8"}, 
	{"name":"Kushala Crus β","part":"legs","rank":"high","slots":["3","0","0"],"skills":[{"id":"31","level":2}],"set_bonus_id":"8"}, 
	{"name":"Vaal Hazak Helm α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"71","level":1},{"id":"24","level":2}],"set_bonus_id":"17"}, 
	{"name":"Vaal Hazak Mail α","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"78","level":2},{"id":"24","level":1}],"set_bonus_id":"17"}, 
	{"name":"Vaal Hazak Braces α","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"71","level":1},{"id":"78","level":1}],"set_bonus_id":"17"}, 
	{"name":"Vaal Hazak Coil α","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"71","level":1},{"id":"28","level":1}],"set_bonus_id":"17"}, 
	{"name":"Vaal Hazak Greaves α","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"28","level":2},{"id":"24","level":1}],"set_bonus_id":"17"}, 
	{"name":"Vaal Hazak Helm β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"71","level":1}],"set_bonus_id":"17"}, 
	{"name":"Vaal Hazak Mail β","part":"chest","rank":"high","slots":["1","1","0"],"skills":[{"id":"78","level":2}],"set_bonus_id":"17"}, 
	{"name":"Vaal Hazak Braces β","part":"arms","rank":"high","slots":["1","1","1"],"skills":[{"id":"71","level":1}],"set_bonus_id":"17"}, 
	{"name":"Vaal Hazak Coil β","part":"waist","rank":"high","slots":["1","1","0"],"skills":[{"id":"71","level":1}],"set_bonus_id":"17"}, 
	{"name":"Vaal Hazak Greaves β","part":"legs","rank":"high","slots":["1","1","0"],"skills":[{"id":"28","level":2}],"set_bonus_id":"17"}, 
	{"name":"Kirin Horn α","part":"head","rank":"high","slots":["0","0","0"],"skills":[{"id":"59","level":2},{"id":"23","level":1}],"set_bonus_id":"7"}, 
	{"name":"Kirin Jacket α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"23","level":2},{"id":"99","level":1}],"set_bonus_id":"7"}, 
	{"name":"Kirin Longarms α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"99","level":2},{"id":"59","level":1}],"set_bonus_id":"7"}, 
	{"name":"Kirin Hoop α","part":"waist","rank":"high","slots":["0","0","0"],"skills":[{"id":"10","level":1},{"id":"39","level":1}],"set_bonus_id":"7"}, 
	{"name":"Kirin Leg Guards α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"39","level":2},{"id":"100","level":2}],"set_bonus_id":"7"}, 
	{"name":"Kirin Horn β","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"59","level":2}],"set_bonus_id":"7"}, 
	{"name":"Kirin Jacket β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"23","level":2}],"set_bonus_id":"7"}, 
	{"name":"Kirin Longarms β","part":"arms","rank":"high","slots":["1","1","0"],"skills":[{"id":"99","level":2}],"set_bonus_id":"7"}, 
	{"name":"Kirin Hoop β","part":"waist","rank":"high","slots":["1","1","1"],"skills":[{"id":"10","level":1}],"set_bonus_id":"7"}, 
	{"name":"Kirin Leg Guards β","part":"legs","rank":"high","slots":["1","1","0"],"skills":[{"id":"39","level":2}],"set_bonus_id":"7"}, 
	{"name":"Xeno'jiiva Headgear α","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"35","level":1},{"id":"89","level":1}],"set_bonus_id":"18"}, 
	{"name":"Xeno'jiiva Hide α","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"75","level":2},{"id":"10","level":1}],"set_bonus_id":"18"}, 
	{"name":"Xeno'jiiva Claws α","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"35","level":1},{"id":"18","level":1}],"set_bonus_id":"18"}, 
	{"name":"Xeno'jiiva Spine α","part":"waist","rank":"high","slots":["3","0","0"],"skills":[{"id":"10","level":2},{"id":"89","level":1}],"set_bonus_id":"18"}, 
	{"name":"Xeno'jiiva Spurs α","part":"legs","rank":"high","slots":["1","0","0"],"skills":[{"id":"35","level":1},{"id":"75","level":1}],"set_bonus_id":"18"}, 
	{"name":"Xeno'jiiva Headgear β","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"35","level":1}],"set_bonus_id":"18"}, 
	{"name":"Xeno'jiiva Hide β","part":"chest","rank":"high","slots":["1","1","0"],"skills":[{"id":"75","level":2}],"set_bonus_id":"18"}, 
	{"name":"Xeno'jiiva Claws β","part":"arms","rank":"high","slots":["3","0","0"],"skills":[{"id":"35","level":1}],"set_bonus_id":"18"}, 
	{"name":"Xeno'jiiva Spine β","part":"waist","rank":"high","slots":["2","1","0"],"skills":[{"id":"10","level":2}],"set_bonus_id":"18"}, 
	{"name":"Xeno'jiiva Spurs β","part":"legs","rank":"high","slots":["1","1","0"],"skills":[{"id":"35","level":1}],"set_bonus_id":"18"}, 
	{"name":"Dragonking Eyepatch α","part":"head","rank":"high","slots":["3","0","0"],"skills":[{"id":"105","level":2}]}, 
	{"name":"Commission Gorget α","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"101","level":1},{"id":"61","level":1}],"set_bonus_id":"3"}, 
	{"name":"Commission Jacket α","part":"chest","rank":"high","slots":["0","0","0"],"skills":[{"id":"106","level":2},{"id":"16","level":1}],"set_bonus_id":"3"}, 
	{"name":"Commission Vambraces α","part":"arms","rank":"high","slots":["1","0","0"],"skills":[{"id":"11","level":1},{"id":"15","level":1}],"set_bonus_id":"3"}, 
	{"name":"Commission Belt α","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"65","level":1},{"id":"76","level":1}],"set_bonus_id":"3"}, 
	{"name":"Commission Pants α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"97","level":2},{"id":"0","level":1}],"set_bonus_id":"3"}, 
	{"name":"Commission Gorget β","part":"head","rank":"high","slots":["2","0","0"],"skills":[{"id":"101","level":1}],"set_bonus_id":"3"}, 
	{"name":"Commission Jacket β","part":"chest","rank":"high","slots":["1","0","0"],"skills":[{"id":"106","level":2}],"set_bonus_id":"3"}, 
	{"name":"Commission Vambraces β","part":"arms","rank":"high","slots":["2","0","0"],"skills":[{"id":"11","level":1}],"set_bonus_id":"3"}, 
	{"name":"Commission Belt β","part":"waist","rank":"high","slots":["2","0","0"],"skills":[{"id":"65","level":1}],"set_bonus_id":"3"}, 
	{"name":"Commission Pants β","part":"legs","rank":"high","slots":["2","0","0"],"skills":[{"id":"97","level":2}],"set_bonus_id":"3"}, 
	{"name":"Sealed Eyepatch α","part":"head","rank":"high","slots":["2","1","0"],"skills":[{"id":"34","level":1}]}, 
	{"name":"Wiggler Head α","part":"head","rank":"high","slots":["1","1","0"],"skills":[{"id":"106","level":2}]}, 
	{"name":"Vangis Helm α","part":"head","rank":"high","slots":["1","0","0"],"skills":[{"id":"70","level":1},{"id":"43","level":1}]}, 
	{"name":"Vangis Mail α","part":"chest","rank":"high","slots":["2","0","0"],"skills":[{"id":"91","level":1},{"id":"43","level":1}]}, 
	{"name":"Vangis Vambraces α","part":"arms","rank":"high","slots":["0","0","0"],"skills":[{"id":"57","level":2},{"id":"70","level":1}]}, 
	{"name":"Vangis Coil α","part":"waist","rank":"high","slots":["1","0","0"],"skills":[{"id":"57","level":1},{"id":"43","level":1}]}, 
	{"name":"Vangis Greaves α","part":"legs","rank":"high","slots":["0","0","0"],"skills":[{"id":"91","level":2},{"id":"70","level":1}]}, 
	{"name":"Vangis Helm β","part":"head","rank":"high","slots":["3","1","0"],"skills":[{"id":"70","level":1}]}, 
	{"name":"Vangis Mail β","part":"chest","rank":"high","slots":["3","0","0"],"skills":[{"id":"91","level":1}]}, 
	{"name":"Vangis Vambraces β","part":"arms","rank":"high","slots":["2","0","0"],"skills":[{"id":"57","level":2}]}, 
	{"name":"Vangis Coil β","part":"waist","rank":"high","slots":["3","1","0"],"skills":[{"id":"57","level":1}]}, 
	{"name":"Vangis Greaves β","part":"legs","rank":"high","slots":["1","1","0"],"skills":[{"id":"91","level":2}]}
];