decorations = [
	{"name":"Slider Jewel 2","level":2,"skills":[{"id":"0","level":1}]}, 
	{"name":"Challenger Jewel 2","level":2,"skills":[{"id":"1","level":1}]}, 
	{"name":"Flight Jewel 1","level":2,"skills":[{"id":"2","level":1}]}, 
	{"name":"Mirewalker Jewel 1","level":1,"skills":[{"id":"3","level":1}]}, 
	{"name":"Artillery Jewel 1","level":1,"skills":[{"id":"4","level":1}]}, 
	{"name":"Attack Jewel 1","level":1,"skills":[{"id":"5","level":1}]}, 
	{"name":"Blast Jewel 1","level":1,"skills":[{"id":"7","level":1}]}, 
	{"name":"Antiblast Jewel 1","level":1,"skills":[{"id":"8","level":1}]}, 
	{"name":"Suture Jewel 1","level":1,"skills":[{"id":"9","level":1}]}, 
	{"name":"Resistor Jewel 1","level":1,"skills":[{"id":"10","level":1}]}, 
	{"name":"Bomber Jewel 1","level":1,"skills":[{"id":"12","level":1}]}, 
	{"name":"Botany Jewel 1","level":1,"skills":[{"id":"13","level":1}]}, 
	{"name":"Magazine Jewel 2","level":2,"skills":[{"id":"14","level":1}]}, 
	{"name":"Physique Jewel 2","level":2,"skills":[{"id":"17","level":1}]}, 
	{"name":"Draw Jewel 2","level":2,"skills":[{"id":"19","level":1}]}, 
	{"name":"Expert Jewel 1","level":1,"skills":[{"id":"20","level":1}]}, 
	{"name":"Defense Jewel 1","level":1,"skills":[{"id":"21","level":1}]}, 
	{"name":"Protection Jewel 1","level":1,"skills":[{"id":"23","level":1}]}, 
	{"name":"Dragon Jewel 1","level":1,"skills":[{"id":"24","level":1}]}, 
	{"name":"Dragon Res Jewel 1","level":1,"skills":[{"id":"25","level":1}]}, 
	{"name":"Earplug Jewel 3","level":3,"skills":[{"id":"27","level":1}]}, 
	{"name":"Miasma Jewel 1","level":1,"skills":[{"id":"28","level":1}]}, 
	{"name":"Specimen Jewel 1","level":1,"skills":[{"id":"30","level":1}]}, 
	{"name":"Jumping Jewel 2","level":2,"skills":[{"id":"31","level":1}]}, 
	{"name":"Evasion Jewel 2","level":2,"skills":[{"id":"32","level":1}]}, 
	{"name":"Blaze Jewel 1","level":1,"skills":[{"id":"33","level":1}]}, 
	{"name":"Fire Res Jewel 1","level":1,"skills":[{"id":"34","level":1}]}, 
	{"name":"Brace Jewel 3","level":3,"skills":[{"id":"35","level":1}]}, 
	{"name":"Charger Jewel 2","level":2,"skills":[{"id":"36","level":1}]}, 
	{"name":"Fortitude Jewel 1","level":1,"skills":[{"id":"38","level":1}]}, 
	{"name":"Release Jewel 3","level":3,"skills":[{"id":"39","level":1}]}, 
	{"name":"Satiated Jewel 1","level":1,"skills":[{"id":"40","level":1}]}, 
	{"name":"Geology Jewel 1","level":1,"skills":[{"id":"41","level":1}]}, 
	{"name":"Ironwall Jewel 1","level":1,"skills":[{"id":"42","level":1}]}, 
	{"name":"Handicraft Jewel 3","level":3,"skills":[{"id":"43","level":1}]}, 
	{"name":"Vitality Jewel 1","level":1,"skills":[{"id":"44","level":1}]}, 
	{"name":"Heavy Artillery Jewel 1","level":1,"skills":[{"id":"46","level":1}]}, 
	{"name":"Potential Jewel 2","level":2,"skills":[{"id":"47","level":1}]}, 
	{"name":"Sonorous Jewel 1","level":1,"skills":[{"id":"49","level":1}]}, 
	{"name":"Hungerless Jewel 1","level":1,"skills":[{"id":"50","level":1}]}, 
	{"name":"Frost Jewel 1","level":1,"skills":[{"id":"51","level":1}]}, 
	{"name":"Ice Res Jewel 1","level":1,"skills":[{"id":"52","level":1}]}, 
	{"name":"Intimidator Jewel 1","level":1,"skills":[{"id":"53","level":1}]}, 
	{"name":"Def Lock Jewel 1","level":1,"skills":[{"id":"54","level":1}]}, 
	{"name":"Enduring Jewel 1","level":1,"skills":[{"id":"55","level":1}]}, 
	{"name":"Throttle Jewel 2","level":2,"skills":[{"id":"57","level":1}]}, 
	{"name":"Sprinter Jewel 2","level":2,"skills":[{"id":"59","level":1}]}, 
	{"name":"Mighty Jewel 2","level":2,"skills":[{"id":"63","level":1}]}, 
	{"name":"Fungiform Jewel 1","level":1,"skills":[{"id":"65","level":1}]}, 
	{"name":"Forceshot Jewel 3","level":3,"skills":[{"id":"66","level":1}]}, 
	{"name":"Meowster Jewel 1","level":1,"skills":[{"id":"67","level":1}]}, 
	{"name":"Paralyzer Jewel 1","level":1,"skills":[{"id":"68","level":1}]}, 
	{"name":"Antipara Jewel 1","level":1,"skills":[{"id":"69","level":1}]}, 
	{"name":"Destroyer Jewel 2","level":2,"skills":[{"id":"70","level":1}]}, 
	{"name":"Flawless Jewel 2","level":2,"skills":[{"id":"71","level":1}]}, 
	{"name":"Pierce Jewel 3","level":3,"skills":[{"id":"72","level":1}]}, 
	{"name":"Venom Jewel 1","level":1,"skills":[{"id":"73","level":1}]}, 
	{"name":"Antidote Jewel 1","level":1,"skills":[{"id":"74","level":1}]}, 
	{"name":"Enhancer Jewel 2","level":2,"skills":[{"id":"75","level":1}]}, 
	{"name":"Sheath Jewel 2","level":1,"skills":[{"id":"77","level":1}]}, 
	{"name":"Recovery Jewel 1","level":1,"skills":[{"id":"78","level":1}]}, 
	{"name":"Medicine Jewel 1","level":1,"skills":[{"id":"79","level":1}]}, 
	{"name":"Furor Jewel 2","level":2,"skills":[{"id":"80","level":1}]}, 
	{"name":"Crisis Jewel 1","level":1,"skills":[{"id":"81","level":1}]}, 
	{"name":"Scent Jewel 1","level":1,"skills":[{"id":"82","level":1}]}, 
	{"name":"Sleep Jewel 1","level":1,"skills":[{"id":"85","level":1}]}, 
	{"name":"Pep Jewel 1","level":1,"skills":[{"id":"86","level":1}]}, 
	{"name":"Stonethrower Jewel 1","level":1,"skills":[{"id":"87","level":1}]}, 
	{"name":"KO Jewel 2","level":2,"skills":[{"id":"88","level":1}]}, 
	{"name":"Trueshot Jewel 1","level":1,"skills":[{"id":"89","level":1}]}, 
	{"name":"Gobbler Jewel 1","level":1,"skills":[{"id":"91","level":1}]}, 
	{"name":"Grinder Jewel 1","level":1,"skills":[{"id":"92","level":1}]}, 
	{"name":"Smoke Jewel 1","level":1,"skills":[{"id":"93","level":1}]}, 
	{"name":"Spread Jewel 3","level":3,"skills":[{"id":"94","level":1}]}, 
	{"name":"Refresh Jewel 2","level":2,"skills":[{"id":"95","level":1}]}, 
	{"name":"Drain Jewel 1","level":1,"skills":[{"id":"96","level":1}]}, 
	{"name":"Tip Toe Jewel 1","level":1,"skills":[{"id":"97","level":1}]}, 
	{"name":"Steadfast Jewel 1","level":1,"skills":[{"id":"98","level":1}]}, 
	{"name":"Bolt Jewel 1","level":1,"skills":[{"id":"99","level":1}]}, 
	{"name":"Thunder Res Jewel 1","level":1,"skills":[{"id":"100","level":1}]}, 
	{"name":"Maintenance Jewel 1","level":1,"skills":[{"id":"101","level":1}]}, 
	{"name":"Footing Jewel 2","level":2,"skills":[{"id":"102","level":1}]}, 
	{"name":"Stream Jewel 1","level":1,"skills":[{"id":"103","level":1}]}, 
	{"name":"Water Res Jewel 1","level":1,"skills":[{"id":"104","level":1}]}, 
	{"name":"Tenderizer Jewel 2","level":2,"skills":[{"id":"105","level":1}]}, 
	{"name":"Friendship Jewel 1","level":1,"skills":[{"id":"106","level":1}]}, 
	{"name":"Wind Resist Jewel 2","level":2,"skills":[{"id":"107","level":1}]}, 
	{"name":"Blastcoat Jewel 3","level":3,"skills":[{"id":"108","level":1}]}, 
	{"name":"Mighty Bow Jewel 2","level":2,"skills":[{"id":"109","level":1}]}, 
	{"name":"Dragonseal Jewel 3","level":3,"skills":[{"id":"110","level":1}]}, 
	{"name":"Shield Jewel 2","level":2,"skills":[{"id":"111","level":1}]}, 
	{"name":"Mind's Eye Jewel 2","level":2,"skills":[{"id":"112","level":1}]}, 
	{"name":"Elementless Jewel 2","level":2,"skills":[{"id":"113","level":1}]}, 
	{"name":"Paracoat Jewel 3","level":3,"skills":[{"id":"114","level":1}]}, 
	{"name":"Poisoncoat Jewel 3","level":3,"skills":[{"id":"115","level":1}]}, 
	{"name":"Sharp Jewel 2","level":2,"skills":[{"id":"116","level":1}]}, 
	{"name":"Sleepcoat Jewel 3","level":3,"skills":[{"id":"117","level":1}]}, 
	{"name":"DUMMY","level":2,"skills":[{"id":"127","level":1}]}, 
	{"name":"Critical Jewel 2","level":2,"skills":[{"id":"18","level":1}]}
];