set_bonus = [
	{"name": "Anjanath Power", "skills": [{"id": "118", "level": 3}]}, 
	{"name": "Anjanath Will", "skills": [{"id": "118", "level": 2}, {"id": "133", "level": 4}]}, 
	{"name": "Bazelgeuse Protection", "skills": [{"id": "125", "level": 3}]}, 
	{"name": "Commission Guidance", "skills": [{"id": "121", "level": 4}]}, 
	{"name": "Diablos Power", "skills": [{"id": "119", "level": 3}]}, 
	{"name": "Diablos Mastery", "skills": [{"id": "119", "level": 2}, {"id": "113", "level": 4}]}, 
	{"name": "Kirin Blessing", "skills": [{"id": "120", "level": 4}]}, 
	{"name": "Kirin Favor", "skills": [{"id": "120", "level": 3}]}, 
	{"name": "Kushala Daora Flight", "skills": [{"id": "129", "level": 3}]}, 
	{"name": "Nergigante Hunger", "skills": [{"id": "126", "level": 3}]}, 
	{"name": "Odogaron Power", "skills": [{"id": "131", "level": 3}]}, 
	{"name": "Odogaron Mastery", "skills": [{"id": "131", "level": 2}, {"id": "116", "level": 4}]}, 
	{"name": "Pink Rathian Mastery", "skills": [{"id": "130", "level": 3}]}, 
	{"name": "Rathalos Power", "skills": [{"id": "122", "level": 3}]}, 
	{"name": "Rathalos Mastery", "skills": [{"id": "122", "level": 2}, {"id": "112", "level": 4}]}, 
	{"name": "Teostra Technique", "skills": [{"id": "127", "level": 3}]}, 
	{"name": "Uragaan Protection", "skills": [{"id": "111", "level": 3}]}, 
	{"name": "Vaal Hazak Vitality", "skills": [{"id": "134", "level": 3}]}, 
	{"name": "Xeno'jiiva Divinity", "skills": [{"id": "132", "level": 3}]}, 
	{"name": "Zorah Magdaros Mastery", "skills": [{"id": "123", "level": 3}]}, 
	{"name": "Legiana Blessing", "skills": [{"id": "124", "level": 3}]}, 
	{"name": "Legiana Favor", "skills": [{"id": "124", "level": 2}, {"id": "109", "level": 4}]}, 
	{"name": "Guild Guidance", "skills": [{"id": "135", "level": 4}]}
];