skills = [
	{"name": "Affinity Sliding", "max_level": 1},
	{"name": "Agitator", "max_level": 5},
	{"name": "Airborne", "max_level": 1},
	{"name": "Aquatic Expert", "max_level": 3},
	{"name": "Artillery", "max_level": 3},
	{"name": "Attack Boost", "max_level": 7},
	{"name": "BBQ Master", "max_level": 1},
	{"name": "Blast Attack", "max_level": 3},
	{"name": "Blast Resistance", "max_level": 3},
	{"name": "Bleeding Resistance", "max_level": 3},
	{"name": "Blight Resistance", "max_level": 3},
	{"name": "Blindsider", "max_level": 1},
	{"name": "Bombardier", "max_level": 3},
	{"name": "Botanist", "max_level": 4},
	{"name": "Capacity Boost", "max_level": 1},
	{"name": "Carving Pro", "max_level": 1},
	{"name": "Cliffhanger", "max_level": 1},
	{"name": "Constitution", "max_level": 5},
	{"name": "Critical Boost", "max_level": 3},
	{"name": "Critical Draw", "max_level": 3},
	{"name": "Critical Eye", "max_level": 7},
	{"name": "Defense Boost", "max_level": 7},
	{"name": "Detector", "max_level": 1},
	{"name": "Divine Blessing", "max_level": 3},
	{"name": "Dragon Attack", "max_level": 5},
	{"name": "Dragon Resistance", "max_level": 3},
	{"name": "Dungmaster", "max_level": 1},
	{"name": "Earplugs", "max_level": 5},
	{"name": "Effluvia Resistance", "max_level": 3},
	{"name": "Effluvial Expert", "max_level": 1},
	{"name": "Entomologist", "max_level": 3},
	{"name": "Evade Extender", "max_level": 3},
	{"name": "Evade Window", "max_level": 5},
	{"name": "Fire Attack", "max_level": 5},
	{"name": "Fire Resistance", "max_level": 3},
	{"name": "Flinch Free", "max_level": 3},
	{"name": "Focus", "max_level": 3},
	{"name": "Forager's Luck", "max_level": 1},
	{"name": "Fortify", "max_level": 1},
	{"name": "Free Elem/Ammo Up", "max_level": 3},
	{"name": "Free Meal", "max_level": 1},
	{"name": "Geologist", "max_level": 3},
	{"name": "Guard", "max_level": 5},
	{"name": "Handicraft", "max_level": 5},
	{"name": "Health Boost", "max_level": 3},
	{"name": "Heat Guard", "max_level": 1},
	{"name": "Heavy Artillery", "max_level": 2},
	{"name": "Heroics", "max_level": 5},
	{"name": "Honey Hunter", "max_level": 1},
	{"name": "Horn Maestro", "max_level": 1},
	{"name": "Hunger Resistance", "max_level": 3},
	{"name": "Ice Attack", "max_level": 5},
	{"name": "Ice Resistance", "max_level": 3},
	{"name": "Intimidator", "max_level": 3},
	{"name": "Iron Skin", "max_level": 3},
	{"name": "Item Prolonger", "max_level": 3},
	{"name": "Jump Master", "max_level": 1},
	{"name": "Latent Power", "max_level": 5},
	{"name": "Leap of Faith", "max_level": 1},
	{"name": "Marathon Runner", "max_level": 3},
	{"name": "Master Fisher", "max_level": 1},
	{"name": "Master Gatherer", "max_level": 1},
	{"name": "Master Mounter", "max_level": 1},
	{"name": "Maximum Might", "max_level": 3},
	{"name": "Muck Resistance", "max_level": 1},
	{"name": "Mushroomancer", "max_level": 3},
	{"name": "Normal Shots", "max_level": 1},
	{"name": "Palico Rally", "max_level": 5},
	{"name": "Paralysis Attack", "max_level": 3},
	{"name": "Paralysis Resistance", "max_level": 3},
	{"name": "Partbreaker", "max_level": 3},
	{"name": "Peak Performance", "max_level": 3},
	{"name": "Piercing Shots", "max_level": 1},
	{"name": "Poison Attack", "max_level": 3},
	{"name": "Poison Resistance", "max_level": 3},
	{"name": "Power Prolonger", "max_level": 3},
	{"name": "Pro Transporter", "max_level": 1},
	{"name": "Quick Sheath", "max_level": 3},
	{"name": "Recovery Speed", "max_level": 3},
	{"name": "Recovery Up", "max_level": 3},
	{"name": "Resentment", "max_level": 5},
	{"name": "Resuscitate", "max_level": 1},
	{"name": "Scenthound", "max_level": 1},
	{"name": "Scholar", "max_level": 1},
	{"name": "Scoutfly Range Up", "max_level": 1},
	{"name": "Sleep Attack", "max_level": 3},
	{"name": "Sleep Resistance", "max_level": 3},
	{"name": "Slinger Capacity", "max_level": 3},
	{"name": "Slugger", "max_level": 3},
	{"name": "Special Ammo Boost", "max_level": 2},
	{"name": "Speed Crawler", "max_level": 1},
	{"name": "Speed Eating", "max_level": 3},
	{"name": "Speed Sharpening", "max_level": 3},
	{"name": "Sporepuff Expert", "max_level": 3},
	{"name": "Spread/Power Shots", "max_level": 1},
	{"name": "Stamina Surge", "max_level": 3},
	{"name": "Stamina Thief", "max_level": 3},
	{"name": "Stealth", "max_level": 3},
	{"name": "Stun Resistance", "max_level": 3},
	{"name": "Thunder Attack", "max_level": 5},
	{"name": "Thunder Resistance", "max_level": 3},
	{"name": "Tool Specialist", "max_level": 3},
	{"name": "Tremor Resistance", "max_level": 3},
	{"name": "Water Attack", "max_level": 5},
	{"name": "Water Resistance", "max_level": 3},
	{"name": "Weakness Exploit", "max_level": 3},
	{"name": "Wide-Range", "max_level": 5},
	{"name": "Windproof", "max_level": 5},
	{"name": "Blast Functionality", "max_level": 1},
	{"name": "Bow Charge Plus", "max_level": 1},
	{"name": "Elderseal Boost", "max_level": 1},
	{"name": "Guard Up", "max_level": 1},
	{"name": "Mind's Eye/Ballistics", "max_level": 1},
	{"name": "Non-elemental Boost", "max_level": 1},
	{"name": "Paralysis Functionality", "max_level": 1},
	{"name": "Poison Functionality", "max_level": 1},
	{"name": "Protective Polish", "max_level": 1},
	{"name": "Sleep Functionality", "max_level": 1},
	{"name": "Adrenaline", "max_level": 1},
	{"name": "Bludgeoner", "max_level": 1},
	{"name": "Capture Master", "max_level": 1},
	{"name": "Carving Master", "max_level": 1},
	{"name": "Critical Element", "max_level": 1},
	{"name": "Critical Status", "max_level": 1},
	{"name": "Good Luck", "max_level": 1},
	{"name": "Guts", "max_level": 1},
	{"name": "Hasten Recovery", "max_level": 1},
	{"name": "Master's Touch", "max_level": 1},
	{"name": "DUMMY", "max_level": 1},
	{"name": "Nullify Wind Pressure", "max_level": 1},
	{"name": "Poison Duration Up", "max_level": 1},
	{"name": "Punishing Draw", "max_level": 1},
	{"name": "Razor Sharp/Spare Shot", "max_level": 1},
	{"name": "Stamina Cap Up", "max_level": 1},
	{"name": "Super Recovery", "max_level": 1}, 
	{"name": "Great Luck", "max_level": 1}, 
	{"name": "Mantle Duration", "max_level": 3}
];